[package]
name = "crafty"
version = "0.1.0"
authors = ["Alex Riedler <alex@riedler.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
